// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbData.proto

package com.appleyk.io.netty.codec2.protobuf.model;

public final class PbData {
  private PbData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SchoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:School)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用dataType来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.School.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     * 用dataType来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.School.DataType data_type = 1;</code>
     * @return The dataType.
     */
    com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType getDataType();

    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getStudent();
    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     */
    com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder getStudentOrBuilder();

    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return Whether the teacher field is set.
     */
    boolean hasTeacher();
    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return The teacher.
     */
    com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getTeacher();
    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     */
    com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder getTeacherOrBuilder();

    public com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code School}
   */
  public  static final class School extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:School)
      SchoolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use School.newBuilder() to construct.
    private School(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private School() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new School();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private School(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_School_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_School_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appleyk.io.netty.codec2.protobuf.model.PbData.School.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.School.Builder.class);
    }

    /**
     * <pre>
     *定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code School.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 在proto3中要求enum的编号需要从0开始
       * </pre>
       *
       * <code>StudentType = 0;</code>
       */
      StudentType(0),
      /**
       * <code>TeacherType = 1;</code>
       */
      TeacherType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 在proto3中要求enum的编号需要从0开始
       * </pre>
       *
       * <code>StudentType = 0;</code>
       */
      public static final int StudentType_VALUE = 0;
      /**
       * <code>TeacherType = 1;</code>
       */
      public static final int TeacherType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return StudentType;
          case 1: return TeacherType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.School.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:School.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STUDENT(2),
      TEACHER(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return TEACHER;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     * 用dataType来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.School.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     * 用dataType来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.School.DataType data_type = 1;</code>
     * @return The dataType.
     */
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType result = com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.valueOf(dataType_);
      return result == null ? com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.UNRECOGNIZED : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return Whether the student field is set.
     */
    public boolean hasStudent() {
      return dataBodyCase_ == 2;
    }
    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     * @return The student.
     */
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getStudent() {
      if (dataBodyCase_ == 2) {
         return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_;
      }
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
    }
    /**
     * <pre>
     * 2是编号
     * </pre>
     *
     * <code>.Student student = 2;</code>
     */
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_;
      }
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
    }

    public static final int TEACHER_FIELD_NUMBER = 3;
    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return Whether the teacher field is set.
     */
    public boolean hasTeacher() {
      return dataBodyCase_ == 3;
    }
    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     * @return The teacher.
     */
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getTeacher() {
      if (dataBodyCase_ == 3) {
         return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_;
      }
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
    }
    /**
     * <pre>
     * 3是编号
     * </pre>
     *
     * <code>.Teacher teacher = 3;</code>
     */
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder getTeacherOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_;
      }
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.StudentType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.StudentType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.School)) {
        return super.equals(obj);
      }
      com.appleyk.io.netty.codec2.protobuf.model.PbData.School other = (com.appleyk.io.netty.codec2.protobuf.model.PbData.School) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getTeacher()
              .equals(other.getTeacher())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.appleyk.io.netty.codec2.protobuf.model.PbData.School prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code School}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:School)
        com.appleyk.io.netty.codec2.protobuf.model.PbData.SchoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_School_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_School_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.appleyk.io.netty.codec2.protobuf.model.PbData.School.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.School.Builder.class);
      }

      // Construct using com.appleyk.io.netty.codec2.protobuf.model.PbData.School.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_School_descriptor;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.School getDefaultInstanceForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.School.getDefaultInstance();
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.School build() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.School result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.School buildPartial() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.School result = new com.appleyk.io.netty.codec2.protobuf.model.PbData.School(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (teacherBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = teacherBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.School) {
          return mergeFrom((com.appleyk.io.netty.codec2.protobuf.model.PbData.School)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.appleyk.io.netty.codec2.protobuf.model.PbData.School other) {
        if (other == com.appleyk.io.netty.codec2.protobuf.model.PbData.School.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.School parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.appleyk.io.netty.codec2.protobuf.model.PbData.School) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       * 用dataType来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.School.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       * 用dataType来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.School.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用dataType来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.School.DataType data_type = 1;</code>
       * @return The dataType.
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType result = com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.valueOf(dataType_);
        return result == null ? com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 用dataType来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.School.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.appleyk.io.netty.codec2.protobuf.model.PbData.School.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用dataType来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.School.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Student, com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder> studentBuilder_;
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       * @return Whether the student field is set.
       */
      public boolean hasStudent() {
        return dataBodyCase_ == 2;
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       * @return The student.
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_;
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(com.appleyk.io.netty.codec2.protobuf.model.PbData.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder mergeStudent(com.appleyk.io.netty.codec2.protobuf.model.PbData.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance()) {
            dataBody_ = com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.newBuilder((com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_;
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 2是编号
       * </pre>
       *
       * <code>.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Student, com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Student, com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder>(
                  (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher, com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder> teacherBuilder_;
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       * @return Whether the teacher field is set.
       */
      public boolean hasTeacher() {
        return dataBodyCase_ == 3;
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       * @return The teacher.
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_;
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return teacherBuilder_.getMessage();
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder mergeTeacher(com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher value) {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance()) {
            dataBody_ = com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.newBuilder((com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder getTeacherOrBuilder() {
        if ((dataBodyCase_ == 3) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_;
          }
          return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 3是编号
       * </pre>
       *
       * <code>.Teacher teacher = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher, com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher, com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder, com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder>(
                  (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return teacherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:School)
    }

    // @@protoc_insertion_point(class_scope:School)
    private static final com.appleyk.io.netty.codec2.protobuf.model.PbData.School DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.appleyk.io.netty.codec2.protobuf.model.PbData.School();
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.School getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<School>
        PARSER = new com.google.protobuf.AbstractParser<School>() {
      @java.lang.Override
      public School parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new School(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<School> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<School> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.School getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teacher();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher)) {
        return super.equals(obj);
      }
      com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher other = (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        com.appleyk.io.netty.codec2.protobuf.model.PbData.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.Builder.class);
      }

      // Construct using com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getDefaultInstanceForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher build() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher buildPartial() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher result = new com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) {
          return mergeFrom((com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher other) {
        if (other == com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher();
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sex = 3;</code>
     * @return The sex.
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 3;</code>
     * @return The bytes for sex.
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>int32 age = 4;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      sex_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            case 32: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private volatile java.lang.Object sex_;
    /**
     * <code>string sex = 3;</code>
     * @return The sex.
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 3;</code>
     * @return The bytes for sex.
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>int32 age = 4;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sex_);
      }
      if (age_ != 0) {
        output.writeInt32(4, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sex_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.Student)) {
        return super.equals(obj);
      }
      com.appleyk.io.netty.codec2.protobuf.model.PbData.Student other = (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getSex()
          .equals(other.getSex())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.appleyk.io.netty.codec2.protobuf.model.PbData.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.appleyk.io.netty.codec2.protobuf.model.PbData.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.class, com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.Builder.class);
      }

      // Construct using com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        sex_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getDefaultInstanceForType() {
        return com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student build() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student buildPartial() {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Student result = new com.appleyk.io.netty.codec2.protobuf.model.PbData.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) {
          return mergeFrom((com.appleyk.io.netty.codec2.protobuf.model.PbData.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.appleyk.io.netty.codec2.protobuf.model.PbData.Student other) {
        if (other == com.appleyk.io.netty.codec2.protobuf.model.PbData.Student.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.appleyk.io.netty.codec2.protobuf.model.PbData.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.appleyk.io.netty.codec2.protobuf.model.PbData.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 3;</code>
       * @return The sex.
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 3;</code>
       * @return The bytes for sex.
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 3;</code>
       * @param value The bytes for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 4;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 4;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.appleyk.io.netty.codec2.protobuf.model.PbData.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.appleyk.io.netty.codec2.protobuf.model.PbData.Student();
    }

    public static com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.appleyk.io.netty.codec2.protobuf.model.PbData.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_School_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_School_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PbData.proto\"\241\001\n\006School\022#\n\tdata_type\030\001" +
      " \001(\0162\020.School.DataType\022\033\n\007student\030\002 \001(\0132" +
      "\010.StudentH\000\022\033\n\007teacher\030\003 \001(\0132\010.TeacherH\000" +
      "\",\n\010DataType\022\017\n\013StudentType\020\000\022\017\n\013Teacher" +
      "Type\020\001B\n\n\010dataBody\"#\n\007Teacher\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\"=\n\007Student\022\n\n\002id\030\001 \001(\003\022\014" +
      "\n\004name\030\002 \001(\t\022\013\n\003sex\030\003 \001(\t\022\013\n\003age\030\004 \001(\005B6" +
      "\n*com.appleyk.io.netty.codec2.protobuf.m" +
      "odelB\006PbDataH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_School_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_School_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_School_descriptor,
        new java.lang.String[] { "DataType", "Student", "Teacher", "DataBody", });
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
